# Project
version=2.8
group=cc.abbie.oldpotions

# Common
minecraft_version=1.21.8

# NeoForge
neo_version=21.8.9

# Fabric
fabric_loader_version=0.16.14
fabric_version=0.129.0+1.21.8

# Dependencies
modmenu_version=15.0.0-beta.3

# Mod options
mod_name=Old Potions
mod_author=Abbie
mod_id=oldpotions

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
